### ISSUE TITLE
Capture Time Query1 Question

### ISSUE THREAD

**Issue by kisingh** [MichaelLukasBauer/TimelyTest#29]
Scenario: The employee defines the working hours in the work profile for Wednesday as 4 hours and the day starts from 9 am[check-in] to 1 pm[check-out] as defined  in the capture time but that day he works 1 hour extra. The overtime is calculated for that day but how the system is notified or gets to know that he worked an extra hour. Do the employee manually  changes the check out time in capture time page or does the employee have to log-in when he comes to work and the time till he is logged-in the system, it automatically  calculates the overtime.  How does the system tracks the overtime?

**Comment by kateryna-sergieieva** [comment]
Working Profile defines official working hours. User start and end time are his real time, when he came and when he left. So if he made 1 hour of overtime, his check-in time - check-out will be equal to 5h, when required is only 4h. So this 1h will go in overtime.
