### ISSUE TITLE
Capture Time Query2-Question

### ISSUE THREAD

**Issue by kisingh** [MichaelLukasBauer/TimelyTest#30]
Scenario:  The employee is going on holidays  from 1st Oct- 15th Oct so he defines it 3 weeks in advance in the capture time but unfortunately his trip got cancelled in the last moment and now he is back to work. So can he change from the holiday to working hours in capture time in the last moment or on the same day [1st Oct].
Is there any regulation that data or some specific data has to be defined or entered in the system prior or in certain time frame? This question I feel is not just for this scenario but in general.

**Comment by kateryna-sergieieva** [comment]
If current month is September and user goes on holiday in October, he won't be able to report these dates till October. 
This rule is based on the Working Profile functionality: Working Profiles exist only from the month app was started being in use till current month, no WP for future monthes, or previous months when app was not in use.
And reporting is only available on the day for which Working Profile exists. In case of example above: there is no Working Profile for October in September, so reporting holidays in October is not possible till October begin and Working Profile for it will be created. When it happens, user will be able to report and change whatever he wants in October.
