### ISSUE TITLE
Capture Time Query3-Question/error

### ISSUE THREAD

**Issue by kisingh** [MichaelLukasBauer/TimelyTest#31]
Scenario: I had defined 13th Sept as a doctor's consultation day and the time was set from 9 am to 17 pm in capture time page. After couple of days I checked my details of 13th Sept  again in capture  time and somehow I was able to make changes in the previous days details which has already passed and the changed data was also getting saved and available on the monthly overview page. for eg: I changed from doctor's consultation to working day and clicked on the save button.I got a pop up msg[data saved]. I tried to log out and login and then check. The capture time page was still showing "working day" which should have been doctor's consultation which was defined the first time.
Is it  possible  to make the changes to the data of past days such as above? What if the employee violates this feature. for example: The employee is on a holiday for a day but he sets as a working day or he changes the working hours, such similar situations.
As CT query3 the employee has the possibility to make changes in  the present and future data but past data I believe shouldn't have this possibility as the data can be manipulated .

**Comment by kateryna-sergieieva** [comment]
No, in current scenario past data is also availbale, because it reflects the real scenario we have with exel sheets.
