### ISSUE TITLE
Generate Final Report1-Question

### ISSUE THREAD

**Issue by kisingh** [MichaelLukasBauer/TimelyTest#32]
Scenario: When the user goes to the generating report page. He selects the month and click on generate report button. A pop message is displayed "allow timley test to allows access media, files". The user selects "allow" than he gets another pop up message that "report saved in documents". Cant the user has the possibility to check or see the final report on the same page as a preview before its gets saved just on one click  in the document. ?

**Comment by kateryna-sergieieva** [comment]
Currently we will provide user with short summary about report. 

But maybe we will add some functionality that user can press on popup "Report Saved" and it'll open pdf doc.
