### ISSUE TITLE
Month Overview- Error

### ISSUE THREAD

**Issue by kisingh** [MichaelLukasBauer/TimelyTest#33]
Scenario:  The working profile is made and the capture time is set for 11th, 12th and 13th Sept. The 3 days are now available or seen on the month overview page.  When I tried to open the capture time details of these days through month overview page. The system stopped working. Pop up msg[ unfortunately timely test has stopped working] resumes again in 1 min.
The system crased for more than 10 times and then finally I could navigate to the capture time page on clicking on the particular date details I want to edit. In this case 13th Sept.

**Comment by kateryna-sergieieva** [comment]
Can not reproduce issue. Issue should be discussed on the meeting.
