### ISSUE TITLE
Working Profile-Error

### ISSUE THREAD

**Issue by kisingh** [MichaelLukasBauer/TimelyTest#34]
Scenario: The employee navigates to working profile, defines the working hours for each day. As one of the constraint, the employee is not allowed to work for more than 10 hours per day. Therefore, he has to set his working hours between 1-10 hours. So when he tries to set 11 hours for one particular day such as Wednesday, a pop up message [ you are not allowed to work more than 10 hours] is displayed when he clicks the save button but there is no changes in the data which he filled. i.e it shows 11h as normal and when the employee clicks again second time on the save button, it gives a pop message[ data saved] which is an error. 
The employee has to navigate to some other page or log out and then visit the working profile page to view the old settings.
Firstly, when the employee clicks on the save button the first time  with the wrong working hours(WH) along with the pop up msg[ you are not allowed to work more than 10 hours] the WH i.e, 11h itself should change to the previous entry or nothing if he had not set anything before or it can turn into red which represents as wrong. And the second thing, on the second click on save button it shouldn't display  " data saved" message as it is WH.

**Comment by kateryna-sergieieva** [comment]
Fixed! Pls check. If it's working, then close.
