### ISSUE TITLE
Change Start and End working time in TimePicker

### ISSUE THREAD

**Issue by kateryna-sergieieva** [MichaelLukasBauer/TimelyTest#8]
When I open Day screen on edit (already created days) and wanna change start or end date, in time picker I see current time, which is on my mashine, but I want to see previously selected one. As shown below on DateTimePicker I wanna see 12:39 not 2:11 pm.

**Comment by kateryna-sergieieva** [comment]
PLS do the same for the break time picker as well! It's assigned 45 mins, when opened it shows 00:00.
And for the TimePickers in Working Profile

**Comment by nbmartial** [comment]
solved
